# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'test1.ui'
#
# Created by: PyQt5 UI code generator 5.10.1
#
# WARNING! All changes made in this file will be lost!

from PyQt5.QtCore import pyqtSignal

from PyQt5.QtWidgets import QApplication
from PyQt5.QtWidgets import QWidget
from PyQt5.QtGui import QImage
from PyQt5.QtGui import QPixmap
from PyQt5.QtCore import QTimer

from PyQt5.QtWidgets import QApplication, QWidget, QPushButton,QGridLayout, \
    QHBoxLayout, QVBoxLayout, QLabel, QSlider, QStyle, QSizePolicy, QFileDialog
from PyQt5.QtWidgets import *
from PyQt5.QtGui import QIcon, QPalette, QImage, QPixmap, QMouseEvent
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtMultimediaWidgets import QVideoWidget
from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import Qt, QUrl, QTimer


from datetime import datetime

#from os import path
#import numpy as np
#import time
#import sys
#import cv2
#import os

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtMultimedia import QMediaPlayer, QMediaContent
from PyQt5.QtMultimediaWidgets import QVideoWidget
class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(977, 789)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.tabWidget = QtWidgets.QTabWidget(Form)
        self.tabWidget.setObjectName("tabWidget")
        self.tab = QtWidgets.QWidget()
        self.tab.setObjectName("tab")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tab)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setSpacing(2)
        self.verticalLayout.setObjectName("verticalLayout")
        self.Cam_1 = QtWidgets.QLabel(self.tab)
        self.Cam_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_1.setScaledContents(True)
        self.Cam_1.setObjectName("Cam_1")
        self.verticalLayout.addWidget(self.Cam_1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.Start_1 = QtWidgets.QPushButton(self.tab)
        self.Start_1.setObjectName("Start_1")
        self.horizontalLayout.addWidget(self.Start_1)
        self.Mon_1 = QtWidgets.QPushButton(self.tab)
        self.Mon_1.setObjectName("Mon_1")
        self.horizontalLayout.addWidget(self.Mon_1)
        self.Car_1 = QtWidgets.QPushButton(self.tab)
        self.Car_1.setObjectName("Car_1")
        self.horizontalLayout.addWidget(self.Car_1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.Stop_1 = QtWidgets.QPushButton(self.tab)
        self.Stop_1.setObjectName("Stop_1")
        self.horizontalLayout_2.addWidget(self.Stop_1)
        self.Per_1 = QtWidgets.QPushButton(self.tab)
        self.Per_1.setObjectName("Per_1")
        self.horizontalLayout_2.addWidget(self.Per_1)
        self.Ill_1 = QtWidgets.QPushButton(self.tab)
        self.Ill_1.setObjectName("Ill_1")
        self.horizontalLayout_2.addWidget(self.Ill_1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 10)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.verticalLayout, 0, 0, 1, 1)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setSpacing(2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.Cam_2 = QtWidgets.QLabel(self.tab)
        self.Cam_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_2.setScaledContents(True)
        self.Cam_2.setObjectName("Cam_2")
        self.verticalLayout_2.addWidget(self.Cam_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.Start_2 = QtWidgets.QPushButton(self.tab)
        self.Start_2.setObjectName("Start_2")
        self.horizontalLayout_3.addWidget(self.Start_2)
        self.Mon_2 = QtWidgets.QPushButton(self.tab)
        self.Mon_2.setObjectName("Mon_2")
        self.horizontalLayout_3.addWidget(self.Mon_2)
        self.Car_2 = QtWidgets.QPushButton(self.tab)
        self.Car_2.setObjectName("Car_2")
        self.horizontalLayout_3.addWidget(self.Car_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.Stop_2 = QtWidgets.QPushButton(self.tab)
        self.Stop_2.setObjectName("Stop_2")
        self.horizontalLayout_4.addWidget(self.Stop_2)
        self.Per_2 = QtWidgets.QPushButton(self.tab)
        self.Per_2.setObjectName("Per_2")
        self.horizontalLayout_4.addWidget(self.Per_2)
        self.Ill_2 = QtWidgets.QPushButton(self.tab)
        self.Ill_2.setObjectName("Ill_2")
        self.horizontalLayout_4.addWidget(self.Ill_2)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.verticalLayout_2.setStretch(0, 10)
        self.verticalLayout_2.setStretch(1, 1)
        self.verticalLayout_2.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_2, 0, 1, 1, 1)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setSpacing(2)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.Cam_3 = QtWidgets.QLabel(self.tab)
        self.Cam_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_3.setScaledContents(True)
        self.Cam_3.setObjectName("Cam_3")
        self.verticalLayout_3.addWidget(self.Cam_3)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.Start_3 = QtWidgets.QPushButton(self.tab)
        self.Start_3.setObjectName("Start_3")
        self.horizontalLayout_5.addWidget(self.Start_3)
        self.Mon_3 = QtWidgets.QPushButton(self.tab)
        self.Mon_3.setObjectName("Mon_3")
        self.horizontalLayout_5.addWidget(self.Mon_3)
        self.Car_3 = QtWidgets.QPushButton(self.tab)
        self.Car_3.setObjectName("Car_3")
        self.horizontalLayout_5.addWidget(self.Car_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.Stop_3 = QtWidgets.QPushButton(self.tab)
        self.Stop_3.setObjectName("Stop_3")
        self.horizontalLayout_6.addWidget(self.Stop_3)
        self.Per_3 = QtWidgets.QPushButton(self.tab)
        self.Per_3.setObjectName("Per_3")
        self.horizontalLayout_6.addWidget(self.Per_3)
        self.Ill_3 = QtWidgets.QPushButton(self.tab)
        self.Ill_3.setObjectName("Ill_3")
        self.horizontalLayout_6.addWidget(self.Ill_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_6)
        self.verticalLayout_3.setStretch(0, 10)
        self.verticalLayout_3.setStretch(1, 1)
        self.verticalLayout_3.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_3, 1, 0, 1, 1)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setSpacing(2)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.Cam_4 = QtWidgets.QLabel(self.tab)
        self.Cam_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_4.setScaledContents(True)
        self.Cam_4.setObjectName("Cam_4")
        self.verticalLayout_4.addWidget(self.Cam_4)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.Start_4 = QtWidgets.QPushButton(self.tab)
        self.Start_4.setObjectName("Start_4")
        self.horizontalLayout_7.addWidget(self.Start_4)
        self.Mon_4 = QtWidgets.QPushButton(self.tab)
        self.Mon_4.setObjectName("Mon_4")
        self.horizontalLayout_7.addWidget(self.Mon_4)
        self.Car_4 = QtWidgets.QPushButton(self.tab)
        self.Car_4.setObjectName("Car_4")
        self.horizontalLayout_7.addWidget(self.Car_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.Stop_4 = QtWidgets.QPushButton(self.tab)
        self.Stop_4.setObjectName("Stop_4")
        self.horizontalLayout_8.addWidget(self.Stop_4)
        self.Per_4 = QtWidgets.QPushButton(self.tab)
        self.Per_4.setObjectName("Per_4")
        self.horizontalLayout_8.addWidget(self.Per_4)
        self.Ill_4 = QtWidgets.QPushButton(self.tab)
        self.Ill_4.setObjectName("Ill_4")
        self.horizontalLayout_8.addWidget(self.Ill_4)
        self.verticalLayout_4.addLayout(self.horizontalLayout_8)
        self.verticalLayout_4.setStretch(0, 10)
        self.verticalLayout_4.setStretch(1, 1)
        self.verticalLayout_4.setStretch(2, 1)
        self.gridLayout_2.addLayout(self.verticalLayout_4, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.mediaPlayer = QMediaPlayer(None, QMediaPlayer.VideoSurface)
        videowidget = QVideoWidget()
        self.openBtn = QtWidgets.QPushButton('Open Video')
        self.playBtn = QtWidgets.QPushButton()
        #self.playBtn.setEnabled(False)
        self.playBtn.setIcon(self.tab_2.style().standardIcon(QStyle.SP_MediaPlay))     
        #self.stopBtn = QtWidgets.QPushButton()
        #self.stopBtn.setIcon(QIcon('stop.png')) 
        self.slowBtn = QtWidgets.QPushButton()
        self.slowBtn.setIcon(self.tab_2.style().standardIcon(QStyle.SP_MediaSeekBackward)) 
        self.fastBtn = QtWidgets.QPushButton()
        self.fastBtn.setIcon(self.tab_2.style().standardIcon(QStyle.SP_MediaSeekForward))     
        self.volumeBtn = QtWidgets.QPushButton()
        self.volumeBtn.setIcon(self.tab_2.style().standardIcon(QStyle.SP_MediaVolume))       
        self.fullscreenBtn = QPushButton("Full Screen")
        self.slider = QSlider(Qt.Horizontal)
        self.slider.setRange(0,0)     
        self.volume_slider = QSlider(Qt.Horizontal)
        self.volume_slider.setRange(0,100)
        self.volume_slider.setValue(50)
        self.label_2_1 = QLabel()
        self.label_2_1.setSizePolicy(QSizePolicy.Preferred, QSizePolicy.Maximum)
        self.label_2_2 = QLabel()
        hboxLayout_2_1 = QHBoxLayout()
        hboxLayout_2_2 = QHBoxLayout()
        hboxLayout_2_3 = QHBoxLayout()
        hboxLayout_2_1.addWidget(self.slider) 
        hboxLayout_2_2.addWidget(self.openBtn)
       #hboxLayout_2_2.addWidget(self.stopBtn)
        hboxLayout_2_2.addWidget(self.slowBtn)
        hboxLayout_2_2.addWidget(self.playBtn)
        hboxLayout_2_2.addWidget(self.fastBtn)
        hboxLayout_2_2.addWidget(self.volumeBtn)
        hboxLayout_2_2.addWidget(self.volume_slider)
        hboxLayout_2_2.addStretch(1)
        hboxLayout_2_2.addWidget(self.fullscreenBtn)      
        hboxLayout_2_3.addWidget(videowidget)
        vboxLayout_2_1 = QVBoxLayout()
        vboxLayout_2_1.addLayout(hboxLayout_2_3)
        vboxLayout_2_1.addLayout(hboxLayout_2_1)
        vboxLayout_2_1.addLayout(hboxLayout_2_2)
        vboxLayout_2_1.addWidget(self.label_2_1)
        self.tab_2.setLayout(vboxLayout_2_1)
        self.mediaPlayer.setVideoOutput(videowidget)


        self.tabWidget.addTab(self.tab_2, "")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tab_3)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout()
        self.verticalLayout_5.setSpacing(2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.Cam_Draw_1 = QtWidgets.QLabel(self.tab_3)
        self.Cam_Draw_1.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_Draw_1.setScaledContents(True)
        self.Cam_Draw_1.setObjectName("Cam_Draw_1")
        self.verticalLayout_5.addWidget(self.Cam_Draw_1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.Draw_1 = QtWidgets.QPushButton(self.tab_3)
        self.Draw_1.setObjectName("Draw_1")
        self.horizontalLayout_9.addWidget(self.Draw_1)
        self.Clear_1 = QtWidgets.QPushButton(self.tab_3)
        self.Clear_1.setObjectName("Clear_1")
        self.horizontalLayout_9.addWidget(self.Clear_1)
        self.verticalLayout_5.addLayout(self.horizontalLayout_9)
        self.verticalLayout_5.setStretch(0, 10)
        self.verticalLayout_5.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_5, 0, 0, 1, 1)
        self.verticalLayout_6 = QtWidgets.QVBoxLayout()
        self.verticalLayout_6.setSpacing(2)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.Cam_Draw_2 = QtWidgets.QLabel(self.tab_3)
        self.Cam_Draw_2.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_Draw_2.setScaledContents(True)
        self.Cam_Draw_2.setObjectName("Cam_Draw_2")
        self.verticalLayout_6.addWidget(self.Cam_Draw_2)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.Draw_2 = QtWidgets.QPushButton(self.tab_3)
        self.Draw_2.setObjectName("Draw_2")
        self.horizontalLayout_10.addWidget(self.Draw_2)
        self.Clear_2 = QtWidgets.QPushButton(self.tab_3)
        self.Clear_2.setObjectName("Clear_2")
        self.horizontalLayout_10.addWidget(self.Clear_2)
        self.verticalLayout_6.addLayout(self.horizontalLayout_10)
        self.verticalLayout_6.setStretch(0, 10)
        self.verticalLayout_6.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_6, 0, 1, 1, 1)
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setSpacing(2)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.Cam_Draw_3 = QtWidgets.QLabel(self.tab_3)
        self.Cam_Draw_3.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_Draw_3.setScaledContents(True)
        self.Cam_Draw_3.setObjectName("Cam_Draw_3")
        self.verticalLayout_7.addWidget(self.Cam_Draw_3)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.Draw_3 = QtWidgets.QPushButton(self.tab_3)
        self.Draw_3.setObjectName("Draw_3")
        self.horizontalLayout_11.addWidget(self.Draw_3)
        self.Clear_3 = QtWidgets.QPushButton(self.tab_3)
        self.Clear_3.setObjectName("Clear_3")
        self.horizontalLayout_11.addWidget(self.Clear_3)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.verticalLayout_7.setStretch(0, 10)
        self.verticalLayout_7.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_7, 1, 0, 1, 1)
        self.verticalLayout_8 = QtWidgets.QVBoxLayout()
        self.verticalLayout_8.setSpacing(2)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.Cam_Draw_4 = QtWidgets.QLabel(self.tab_3)
        self.Cam_Draw_4.setFrameShape(QtWidgets.QFrame.Box)
        self.Cam_Draw_4.setScaledContents(True)
        self.Cam_Draw_4.setObjectName("Cam_Draw_4")
        self.verticalLayout_8.addWidget(self.Cam_Draw_4)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.Draw_4 = QtWidgets.QPushButton(self.tab_3)
        self.Draw_4.setObjectName("Draw_4")
        self.horizontalLayout_12.addWidget(self.Draw_4)
        self.Clear_4 = QtWidgets.QPushButton(self.tab_3)
        self.Clear_4.setObjectName("Clear_4")
        self.horizontalLayout_12.addWidget(self.Clear_4)
        self.verticalLayout_8.addLayout(self.horizontalLayout_12)
        self.verticalLayout_8.setStretch(0, 10)
        self.verticalLayout_8.setStretch(1, 1)
        self.gridLayout_3.addLayout(self.verticalLayout_8, 1, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, "")
        self.gridLayout.addWidget(self.tabWidget, 0, 0, 1, 1)

        self.retranslateUi(Form)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Cam_1.setText(_translate("Form", "Cam_1"))
        self.Start_1.setText(_translate("Form", "Start"))
        self.Mon_1.setText(_translate("Form", "Monitor Prohibited Area"))
        self.Car_1.setText(_translate("Form", "Car Protection"))
        self.Stop_1.setText(_translate("Form", "Stop"))
        self.Per_1.setText(_translate("Form", "Person Searching"))
        self.Ill_1.setText(_translate("Form", "Illegal Access Action"))
        self.Cam_2.setText(_translate("Form", "Cam_2"))
        self.Start_2.setText(_translate("Form", "Start"))
        self.Mon_2.setText(_translate("Form", "Monitor Prohibited Area"))
        self.Car_2.setText(_translate("Form", "Car Protection"))
        self.Stop_2.setText(_translate("Form", "Stop"))
        self.Per_2.setText(_translate("Form", "Person Searching"))
        self.Ill_2.setText(_translate("Form", "Illegal Access Action"))
        self.Cam_3.setText(_translate("Form", "Cam_3"))
        self.Start_3.setText(_translate("Form", "Start"))
        self.Mon_3.setText(_translate("Form", "Monitor Prohibited Area"))
        self.Car_3.setText(_translate("Form", "Car Protection"))
        self.Stop_3.setText(_translate("Form", "Stop"))
        self.Per_3.setText(_translate("Form", "Person Searching"))
        self.Ill_3.setText(_translate("Form", "Illegal Access Action"))
        self.Cam_4.setText(_translate("Form", "Cam_4"))
        self.Start_4.setText(_translate("Form", "Start"))
        self.Mon_4.setText(_translate("Form", "Monitor Prohibited Area"))
        self.Car_4.setText(_translate("Form", "Car Protection"))
        self.Stop_4.setText(_translate("Form", "Stop"))
        self.Per_4.setText(_translate("Form", "Person Searching"))
        self.Ill_4.setText(_translate("Form", "Illegal Access Action"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("Form", "Tab 1"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("Form", "Tab 2"))
        self.Cam_Draw_1.setText(_translate("Form", "Cam_1"))
        self.Draw_1.setText(_translate("Form", "Draw"))
        self.Clear_1.setText(_translate("Form", "Clear"))
        self.Cam_Draw_2.setText(_translate("Form", "Cam_2"))
        self.Draw_2.setText(_translate("Form", "Draw"))
        self.Clear_2.setText(_translate("Form", "Clear"))
        self.Cam_Draw_3.setText(_translate("Form", "Cam_3"))
        self.Draw_3.setText(_translate("Form", "Draw"))
        self.Clear_3.setText(_translate("Form", "Clear"))
        self.Cam_Draw_4.setText(_translate("Form", "Cam_4"))
        self.Draw_4.setText(_translate("Form", "Draw"))
        self.Clear_4.setText(_translate("Form", "Clear"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Form", "Tab 3"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())